### ISSUE TITLE
Performance test: May 21st, 2024 - Blue/TST: ML ver11.0.3 downgraded

### ISSUE THREAD

**Issue by jffcamp** [project-lux/lux-marklogic#150]
**Primary objective:** We are running this performance test to replicate the good performance test results run last year (Scenario J).

**Differences since last test:** Three performance tests were executed under #132.  We were unable to reproduce Scenario J's outcome.  This test is expected to be the equivalent of test no. 2 but in Blue and after restarting the ec2 instances.  Blue also has ML 11.0.3 with remnants of a nightly build of ML 11.2.0.

1. TST environment with Green backend resolving name search criteria against primary and alternative names.  ML 11.0.3 with remnants of a nightly build of ML 11.2.0.
2. **TST environment with Green backend resolving name search criteria against primary names alone.  ML 11.0.3 with remnants of a nightly build of ML 11.2.0.**
3. DEV environment with clean install of ML 11.2.0 GA.

**Environment and versions: Blue (as TST)** comprised of MarkLogic 11.0.3 (downgraded from 11.2 early release), Backend v1.16.0, Middle Tier v1.1.9, Frontend v1.26, and Dataset produced on 2024-04-18.

**Scenario AI** of the [Perf Test Line Up](https://docs.google.com/spreadsheets/d/1uu6aL7yn047yyiZ4auujpTXnlwm01sgWZQ50ht-X4M4/edit#gid=593469390): our existing dual app server configuration (Scenario J) but after replacing the ec2 instances.  ML 11.0.3 environment with remnants of a nightly build of ML 11.2.0.

Key metrics we're targeting (column E / scenario J):

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/a6a5561e-8030-4180-b91d-92d120872db0)

Number of application servers: 2 per node.
Maximum number of concurrent application server threads:

- lux-request-group-2: 12 per node for search and related list requests
- lux-request-group-1: 6 per node for all other request types
- total: 18 per node

For more information please see the documentation: [LUX Performance Testing Procedure](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md)

**Tasks to complete:**

- ~~[ ] Deploy Backend v1.16.0 with the `fullTextSearchRelatedFieldName` build property set to `referenceName`.~~
- ~~[ ] In QC, verify /lib/appConstants.mjs includes `const FULL_TEXT_SEARCH_RELATED_FIELD_NAME = 'referenceName'.trim();`~~
- [x] Disable Blue's middle-tier caching.
- [x] Xinjian: Restart the EC2 MarkLogic nodes <-- unique aspect of #150
- [x] Verify LUX trace events are enabled plus `v8 delay timeout`.
- [x] Smoke test the front end.
- [x] Xinjian: Start collecting OS-level metrics.
- [x] Peter: Start collecting middle tier metrics ([getMiddleTierStats.sh](https://git.yale.edu/lux-its/marklogic/blob/main/scripts/getMiddleTierStats.sh))
- [x] QA: Verify/set ramp-up schedule to 2 simple search VUs, 1 filtered VU, and 1 entity page VU every three minutes until there are 148 users then hold for 15 minutes.
- [x] QA: Verify scripts point to BLUE/TST, https://lux-front-tst.collections.yale.edu/
- [x] Team: Sign off on the above before proceeding.
- [x] QA: Start performance test
- [x] QA: Finish performance test

**Data collection** ([Details from procedure](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md#collect-data)):

- [x] Xinjian: Stop collecting OS-level metrics and attach to the ticket
- [x] Peter: Stop collecting middle-tier metrics and attach to the ticket
- [ ] Xinjian: Collect data from AWS and attach to ticket.
- [x] Xinjian: Download the monitoring history (level=raw) and attach to the ticket.
- [ ] Xinjian: Take screenshots of select monitoring history graphs.
- [ ] Brent: Collect, trim, and attach backend logs to the ticket.
- [ ] Brent: Pull app server queue metrics, attach to the ticket, and record in [Perf: Key Metrics](https://docs.google.com/spreadsheets/d/1uu6aL7yn047yyiZ4auujpTXnlwm01sgWZQ50ht-X4M4/edit#gid=774672157).
- [ ] TBD: Update online spreadsheet tabs with what is known at this point.

**Revert all configuration changes:**

- ~~[ ] Deploy Backend v1.16.0 with the `fullTextSearchRelatedFieldName` build property set to `referencePrimaryName`.~~
- [x] Enable middle-tier caching.

**Verify:**

- [ ] Smoke test the front end.

**Analysis:**

- [ ] TBD: Upon receipt, review report from QA and update related portions of the online spreadsheet tabs.
- [ ] TBD: Mine the backend logs?
- [ ] TBD: Determine if the test is valid.
- [ ] TBD: Determine if the performance is acceptable --> #100.

**Comment by jffcamp** [comment]
One of Brent's grep commands
grep -v Info ErrorLog.txt | grep -v Debug

**Comment by clarkepeterf** [comment]
Middle tier stats:[20240521-tst-middle-tier-stats.txt](https://github.com/project-lux/lux-marklogic/files/15394483/20240521-tst-middle-tier-stats.txt)

**Comment by jffcamp** [comment]
Start Time: 12:57:16 pm EST
End Time: 3:06:58 pm EST

**Comment by xinjianguo** [comment]
on all 3 ML nodes
```
cd /tmp
ls -l sar*05-51*
sudo gzip sar*05-21*
```
on local desktop:
```
cd ~/Apps/LUX/marklogic/scripts/logAnalysis
mkdir ~/Apps/LUX/ML/test/20240521
vi collectBackendLogs.sh
./collectBackendLogs.sh
```

**Comment by xinjianguo** [comment]
OS metrics

[sar_ip-10-5-156-62.its.yale.edu_2024-05-21T165212_screen.out.gz](https://github.com/project-lux/lux-marklogic/files/15394841/sar_ip-10-5-156-62.its.yale.edu_2024-05-21T165212_screen.out.gz)
[sar_ip-10-5-156-62.its.yale.edu_2024-05-21T165212.out.gz](https://github.com/project-lux/lux-marklogic/files/15394842/sar_ip-10-5-156-62.its.yale.edu_2024-05-21T165212.out.gz)
[sar_ip-10-5-157-203.its.yale.edu_2024-05-21T165215_screen.out.gz](https://github.com/project-lux/lux-marklogic/files/15394843/sar_ip-10-5-157-203.its.yale.edu_2024-05-21T165215_screen.out.gz)
[sar_ip-10-5-157-203.its.yale.edu_2024-05-21T165215.out.gz](https://github.com/project-lux/lux-marklogic/files/15394844/sar_ip-10-5-157-203.its.yale.edu_2024-05-21T165215.out.gz)
[sar_ip-10-5-254-44.its.yale.edu_2024-05-21T165217_screen.out.gz](https://github.com/project-lux/lux-marklogic/files/15394845/sar_ip-10-5-254-44.its.yale.edu_2024-05-21T165217_screen.out.gz)
[sar_ip-10-5-254-44.its.yale.edu_2024-05-21T165217.out.gz](https://github.com/project-lux/lux-marklogic/files/15394846/sar_ip-10-5-254-44.its.yale.edu_2024-05-21T165217.out.gz)

**Comment by xinjianguo** [comment]
ML CPU details
![Screen Shot 2024-05-21 at 3 30 03 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/3dc024a1-e862-442a-bf62-d3207b614dfd)
![Screen Shot 2024-05-21 at 3 30 13 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/96e61fad-092e-44ed-9b04-932940a89f6f)

ML Memory details
![Screen Shot 2024-05-21 at 3 35 24 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/24bbdd02-8896-43bb-b5cb-4dcd13dfbfbe)
![Screen Shot 2024-05-21 at 3 35 47 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/078b451a-91ba-4c4a-bd2f-7d9376aed49b)
![Screen Shot 2024-05-21 at 3 35 59 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/5df4eabd-17a3-4c71-a14c-2276691c6f8a)
![Screen Shot 2024-05-21 at 3 36 08 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/b48f303c-4d5a-4976-a32c-04799f184c54)

**Comment by xinjianguo** [comment]
OS CPU
![Screen Shot 2024-05-21 at 3 16 14 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/cf24bd5c-fb77-4b0d-8f43-f6fcc5717696)

ALB
![Screen Shot 2024-05-21 at 3 18 29 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/2654fb56-2500-4fa7-9a34-5b1f73615e8b)
![Screen Shot 2024-05-21 at 3 19 06 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/f60efaa8-241d-48e8-91c1-be80b0ca4a75)
![Screen Shot 2024-05-21 at 3 18 56 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/55147a82-8ae7-4e16-b4a0-7a684394fc1d)
![Screen Shot 2024-05-21 at 3 18 45 PM](https://github.com/project-lux/lux-marklogic/assets/11890647/285f37f0-ac61-4574-9088-8aedc6fe5b27)

**Comment by brent-hartwig** [comment]
Unknown why the request count was closer amongst the nodes.  Note that the node with the fewest requests also consistently reported higher CPU utilization.

| Node | Request Count | % of |
| --- | --- | --- |
| 22 | 56,590 | 90% |
| 111 | 59,499 | 95% |
| 217 | 62,721 | 100% |

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/4d83f478-1f1f-4d95-bddd-ab4e302e42c7)

**Comment by xinjianguosccs** [comment]
@brent-hartwig oh I thought we only need the graphs, will capture exports as well

**Comment by jffcamp** [comment]
Results invalidated. QA lost 10 flows due to a UI change. This caused a single flow failure and prevented all following flows from running.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing as this ticket was marked as Done the week of 6/3.
