### ISSUE TITLE
Performance Test - scheduled for 2024-06-18

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#181]
## Primary Objective
Scenario AK in the [Perf Test Line Up](https://docs.google.com/spreadsheets/d/1uu6aL7yn047yyiZ4auujpTXnlwm01sgWZQ50ht-X4M4/edit#gid=593469390): With Scenario AK (#162) as this test's baseline, quantify the performance impact of including alternative names in keyword and name search criteria.

## Changes Being Tested
#100 on top of paginated facet requests (#160 and #161), which is part of the baseline test (#162).  #100's changes:

1. The related documents portion of the keyword search pattern switched from the `referencePrimaryName` field to the `referenceName` field.  By search scope, here are the record types that included or excluded from reference fields:
    * Included:
        * Agent: Group, Person
        * Concept: Language, MeasurementUnit, Type
        * Event: Activity, Period
        * Place: Place
    * Excluded:
        * Concept: Currency, Material
        * Item: DigitalObject, HumanMadeObject
        * Work: LinguisticObject, Set, VisualItem
3. All `name` search terms less the `set` search scope switched from their search scope-specific primary name field to their broader name field; for instance, the `name` search term in the `agent` scope was changed from `agentPrimaryName` to `agentName`.

### Environment and Versions

- Environment: TST which is configured to the **Blue** backend.
- MarkLogic **11.2.0 GA**
- Backend branch **TODO**, which is comprised of:
    - [v1.17.0](https://github.com/project-lux/lux-marklogic/tree/v1.17.0)
    - Paginated facets (#160 + #161)
    - Alternative names in name search (#100)
- Middle Tier **v1.1.9 + facet pagination**
- Frontend **v1.27.0 + facet pagination**
- Dataset produced on **2024-05-14** <-- #162 was against 2024-05-29.

### Backend Application Server Configuration

- lux-request-group-1 on port 8003: The middle tier is expected to send all requests here **except** search and relatedList requests.  Maximum of 6 concurrent requests.
- lux-request-group-2 on port 8004: The middle tier is expected to send all search and relatedList requests to this application server.  Maximum of 12 concurrent requests.
- Maximum of 18 concurrent requests per node.

## Tasks

For more information please see the documentation: [LUX Performance Testing Procedure](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md)

### Prep, Start, and Preliminary Checks

- [x] Confirm the most recent blue-green switch is 100% complete (i.e., no part of TST is using PROD).
- [x] Deploy code and/or configuration changes that are being tested.
- [x] Disable middle-tier caching in TST ([instructions](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md#disable-middle-tier-caching)).
- [x] Verify LUX trace events are enabled plus `v8 delay timeout`.
- [x] Smoke test the front end.
- [x] Start collecting OS-level metrics ([instructions](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md#start-collecting-os-level-metrics)).
- [x] Start collecting middle tier metrics ([script](https://git.yale.edu/lux-its/marklogic/blob/main/scripts/getMiddleTierStats.sh))
- [x] QA: Verify/set ramp-up schedule to 2 simple search VUs, 1 filtered VU, and 1 entity page VU every three minutes until there are 148 users then hold for 15 minutes.
- [x] QA: Verify test is configured with three second wait times.
- [x] QA: Verify scripts point to TST, https://lux-front-tst.collections.yale.edu/
- [x] Team: Sign off on the above before proceeding.
- [x] QA: Start performance test. Start Time -- 12:48:51 PM
- [x] Team: begin monitoring for v8 engine crashes.
- [x] Team: check total request count at 10 minutes.
- [x] Team: check total request count at 15 minutes.
- [x] Team: check total request count at 20 minutes.
- [x] QA: Finish performance test. End Time -- 2:58:32 PM

### Collect data

- [x] Stop collecting OS-level metrics and attach to the ticket.
- [x] Stop collecting middle-tier metrics and attach to the ticket.
- [x] Collect data from AWS and attach to ticket.
- [x] Collect ML monitoring history ([instructions](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md#backend-monitoring-history)).
- [x] Collect ([script](https://github.com/project-lux/lux-marklogic/blob/main/scripts/logAnalysis/collectBackendLogs.sh)), trim ([script](https://github.com/project-lux/lux-marklogic/blob/main/scripts/logAnalysis/trimBackendLogs.sh)), and attach backend logs to the ticket.
- [ ] Pull app server queue metrics ([script](https://github.com/project-lux/lux-marklogic/blob/main/scripts/extractAppServerQueueMetrics.js)), attach to the ticket, and record in [Perf: Key Metrics](https://docs.google.com/spreadsheets/d/1uu6aL7yn047yyiZ4auujpTXnlwm01sgWZQ50ht-X4M4/edit#gid=774672157).  *Starting in ML 11.2.0, this information may be included in the ML monitoring history screenshots and exports.*
- [ ] Update online spreadsheet tabs with what is known at this point.

### Restore and Verify Environment

- [x] Revert this test's code and configuration changes
- [x] Enable middle-tier caching ([instructions](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md#enable-middle-tier-caching)).
- [x] Smoke test the front end.

### Analyze

- [ ] Upon receipt, review report from QA and update related portions of the online spreadsheet tabs.
- [x] Mine the backend logs?  _Yes.  Results are included in multiple comments._
- [ ] Determine if the test is valid.
- [ ] Determine if the performance is acceptable.

### Notes
- Test duration: 12:48:51 - 2:58:32 p.m.

**Comment by brent-hartwig** [comment]
Verified in Blue:

1. FULL_TEXT_SEARCH_RELATED_FIELD_NAME = 'referenceName'
2. 7 of 8 name search terms switched to include alternative names.
3. Pagination support for facets.

cc: @clarkepeterf

**Comment by clarkepeterf** [comment]
Middle tier stats:
[20240618-tst-middle-tier-stats.txt](https://github.com/user-attachments/files/15891523/20240618-tst-middle-tier-stats.txt)

**Comment by xinjianguo** [comment]
ML load balancer:
![perf-test-20240618-ML-ALB](https://github.com/project-lux/lux-marklogic/assets/11890647/946ff26a-77a4-4b34-a9b6-b7ed6f1576e0)

CPU utilization of ML nodes:
![perf-test-20240618-ML-ec2-CPU](https://github.com/project-lux/lux-marklogic/assets/11890647/3f316c5b-911b-4223-8169-582d9f426253)

504s from ML load balancer:
![perf-test-20240618-ML-ALB-504](https://github.com/project-lux/lux-marklogic/assets/11890647/787a16c4-e3c8-4a99-9d6c-17f1b40a7971)

504s from web cache:
![perf-test-20240618-webcache-ALB-504](https://github.com/project-lux/lux-marklogic/assets/11890647/900c0591-e288-4785-82f1-2c9a4fb5bfec)

**Comment by xinjianguo** [comment]
OS-level metrics:

on all 3 ML nodes
```
cd /tmp
ls -l sar*06-18*
sudo gzip sar*06-18*
```

on local:
cd ~/Apps/LUX/marklogic/scripts/logAnalysis
mkdir ~/Apps/LUX/ML/test/20240618
vi collectBackendLogs.sh
./collectBackendLogs.sh

[sar_ip-10-5-156-239.its.yale.edu_2024-06-18T165429_screen.out.gz](https://github.com/user-attachments/files/15891681/sar_ip-10-5-156-239.its.yale.edu_2024-06-18T165429_screen.out.gz)
[sar_ip-10-5-156-239.its.yale.edu_2024-06-18T165429.out.gz](https://github.com/user-attachments/files/15891683/sar_ip-10-5-156-239.its.yale.edu_2024-06-18T165429.out.gz)
[sar_ip-10-5-157-48.its.yale.edu_2024-06-18T165441_screen.out.gz](https://github.com/user-attachments/files/15891684/sar_ip-10-5-157-48.its.yale.edu_2024-06-18T165441_screen.out.gz)
[sar_ip-10-5-157-48.its.yale.edu_2024-06-18T165441.out.gz](https://github.com/user-attachments/files/15891685/sar_ip-10-5-157-48.its.yale.edu_2024-06-18T165441.out.gz)
[sar_ip-10-5-254-35.its.yale.edu_2024-06-18T165459_screen.out.gz](https://github.com/user-attachments/files/15891686/sar_ip-10-5-254-35.its.yale.edu_2024-06-18T165459_screen.out.gz)
[sar_ip-10-5-254-35.its.yale.edu_2024-06-18T165459.out.gz](https://github.com/user-attachments/files/15891687/sar_ip-10-5-254-35.its.yale.edu_2024-06-18T165459.out.gz)

**Comment by gigamorph** [comment]
### Status code counts
CloudFront (non-frontend routes):
![perf-cf-api-data](https://github.com/project-lux/lux-marklogic/assets/86015/8d337bfe-1a6e-4452-a9f3-699b38aabb08)

WebCache ALB:
![perf-webcache-alb](https://github.com/project-lux/lux-marklogic/assets/86015/fce43fa9-bf27-4183-8f09-1e70ccfc7b73)

Middle tier ALB:
![perf-middle-alb](https://github.com/project-lux/lux-marklogic/assets/86015/1d1d5dfd-4d43-4dd4-9468-604e951e3900)

MarkLogic ALB:
![perf-marklogic-alb](https://github.com/project-lux/lux-marklogic/assets/86015/6b079b49-6bef-4b2e-8313-5f8c577eff7a)

**Comment by brent-hartwig** [comment]
ML monitoring exports:

[memory-detail-20240618-191008.xls](https://github.com/user-attachments/files/15892147/memory-detail-20240618-191008.xls)
[network-detail-20240618-191309.xls](https://github.com/user-attachments/files/15892149/network-detail-20240618-191309.xls)
[overview-20240618-190841.xls](https://github.com/user-attachments/files/15892150/overview-20240618-190841.xls)
[servers-detail-20240618-191130.xls](https://github.com/user-attachments/files/15892153/servers-detail-20240618-191130.xls)
[xdqp-server requests detail-20240618-191041.xls](https://github.com/user-attachments/files/15892155/xdqp-server.requests.detail-20240618-191041.xls)
[cpu-detail-20240618-190721.xls](https://github.com/user-attachments/files/15892156/cpu-detail-20240618-190721.xls)
[databases-detail-20240618-201419.xls](https://github.com/user-attachments/files/15892157/databases-detail-20240618-201419.xls)
[file-i_o detail-20240618-190924.xls](https://github.com/user-attachments/files/15892164/file-i_o.detail-20240618-190924.xls)

**Comment by brent-hartwig** [comment]
## ML Monitoring History

Time period: 1649 - 1900 UTC

CPU:

![01-cpu](https://github.com/project-lux/lux-marklogic/assets/13734146/06212145-6885-4c4b-a768-e0aae690bf0d)

File IO Detail:

![02-file-io](https://github.com/project-lux/lux-marklogic/assets/13734146/f1efd33f-7b99-4472-acaa-a964409dbe3a)

Memory:

![03-memory](https://github.com/project-lux/lux-marklogic/assets/13734146/7536b649-74f1-408d-95c7-e614745471b2)

Intra-cluster activity, 1 of 2:

![04-intra-cluster-1-of-2](https://github.com/project-lux/lux-marklogic/assets/13734146/d978102c-3da3-4490-a552-01b4671c6f46)

Intra-cluster activity, 2 of 2:

![05-intra-cluster-2-of-2](https://github.com/project-lux/lux-marklogic/assets/13734146/57d2401e-6329-4d8b-b76c-59de6c0d85dd)

Both HTTP app servers:

![06-http-servers](https://github.com/project-lux/lux-marklogic/assets/13734146/bac5eedc-d589-4c26-ae3c-743ffd73e0d5)

Just the `lux-request-group-1` app server (all requests here except `search` and `relatedList` requests, up to 6 threads per node):

Note the difference in the y axes for `lux-request-group-1` and `lux-request-group-2`.

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/31105eef-7e2d-458a-989e-75cab13f2398)

Just the `lux-request-group-2` app server (just `search` and `relatedList` requests, up to 12 threads per node):

Note the difference in the y axes for `lux-request-group-1` and `lux-request-group-2`.

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/8cc8f3d4-c31f-4fb3-a4cc-9204804c5459)

Data node characteristics for the `lux-content` database alone:

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/53b7922f-561b-474e-a395-7cc1e2f70440)

**Comment by brent-hartwig** [comment]
Trimmed backend logs:

[20240618-blue-as-test-node-217-ErrorLog-trimmed.zip](https://github.com/user-attachments/files/15892428/20240618-blue-as-test-node-217-ErrorLog-trimmed.zip)
[20240618-blue-as-test-node-217-8004-RequestLog-trimmed.zip](https://github.com/user-attachments/files/15892430/20240618-blue-as-test-node-217-8004-RequestLog-trimmed.zip)
[20240618-blue-as-test-node-217-8004-ErrorLog-trimmed.zip](https://github.com/user-attachments/files/15892431/20240618-blue-as-test-node-217-8004-ErrorLog-trimmed.zip)
[20240618-blue-as-test-node-217-8004-AccessLog-trimmed.zip](https://github.com/user-attachments/files/15892433/20240618-blue-as-test-node-217-8004-AccessLog-trimmed.zip)
[20240618-blue-as-test-node-217-8003-RequestLog-trimmed.zip](https://github.com/user-attachments/files/15892434/20240618-blue-as-test-node-217-8003-RequestLog-trimmed.zip)
[20240618-blue-as-test-node-217-8003-ErrorLog-trimmed.zip](https://github.com/user-attachments/files/15892437/20240618-blue-as-test-node-217-8003-ErrorLog-trimmed.zip)
[20240618-blue-as-test-node-217-8003-AccessLog-trimmed.zip](https://github.com/user-attachments/files/15892444/20240618-blue-as-test-node-217-8003-AccessLog-trimmed.zip)
[20240618-blue-as-test-node-111-ErrorLog-trimmed.zip](https://github.com/user-attachments/files/15892447/20240618-blue-as-test-node-111-ErrorLog-trimmed.zip)
[20240618-blue-as-test-node-111-8004-RequestLog-trimmed.zip](https://github.com/user-attachments/files/15892449/20240618-blue-as-test-node-111-8004-RequestLog-trimmed.zip)
[20240618-blue-as-test-node-111-8004-ErrorLog-trimmed.zip](https://github.com/user-attachments/files/15892404/20240618-blue-as-test-node-111-8004-ErrorLog-trimmed.zip)
[20240618-blue-as-test-node-111-8004-AccessLog-trimmed.zip](https://github.com/user-attachments/files/15892406/20240618-blue-as-test-node-111-8004-AccessLog-trimmed.zip)
[20240618-blue-as-test-node-111-8003-RequestLog-trimmed.zip](https://github.com/user-attachments/files/15892407/20240618-blue-as-test-node-111-8003-RequestLog-trimmed.zip)
[20240618-blue-as-test-node-111-8003-ErrorLog-trimmed.zip](https://github.com/user-attachments/files/15892408/20240618-blue-as-test-node-111-8003-ErrorLog-trimmed.zip)
[20240618-blue-as-test-node-111-8003-AccessLog-trimmed.zip](https://github.com/user-attachments/files/15892409/20240618-blue-as-test-node-111-8003-AccessLog-trimmed.zip)
[20240618-blue-as-test-node-22-ErrorLog-trimmed.zip](https://github.com/user-attachments/files/15892413/20240618-blue-as-test-node-22-ErrorLog-trimmed.zip)
[20240618-blue-as-test-node-22-8004-RequestLog-trimmed.zip](https://github.com/user-attachments/files/15892416/20240618-blue-as-test-node-22-8004-RequestLog-trimmed.zip)
[20240618-blue-as-test-node-22-8004-ErrorLog-trimmed.zip](https://github.com/user-attachments/files/15892417/20240618-blue-as-test-node-22-8004-ErrorLog-trimmed.zip)
[20240618-blue-as-test-node-22-8004-AccessLog-trimmed.zip](https://github.com/user-attachments/files/15892418/20240618-blue-as-test-node-22-8004-AccessLog-trimmed.zip)
[20240618-blue-as-test-node-22-8003-RequestLog-trimmed.zip](https://github.com/user-attachments/files/15892419/20240618-blue-as-test-node-22-8003-RequestLog-trimmed.zip)
[20240618-blue-as-test-node-22-8003-ErrorLog-trimmed.zip](https://github.com/user-attachments/files/15892421/20240618-blue-as-test-node-22-8003-ErrorLog-trimmed.zip)
[20240618-blue-as-test-node-22-8003-AccessLog-trimmed.zip](https://github.com/user-attachments/files/15892425/20240618-blue-as-test-node-22-8003-AccessLog-trimmed.zip)

**Comment by brent-hartwig** [comment]
- [ ] Resolved / Understood

About 25 minutes into the test, utilization rates dropped in the backend.  Up to that point, there was a single `JS-FATAL` instance, which we first observed in #162, but the database remained available and no ML process restarted.  Seong was unable to find evidence of a crash higher in the stack.  Yisha looked at the LoadRunner side but also could not come up with an explanation.  It was the only such instance (back-to-back instances) during this test.

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/9fc402c3-e34c-4c69-9134-bd6fd2193f30)

**Comment by brent-hartwig** [comment]
@prowns, @jffcamp, and @clarkepeterf, below is a comparison between the baseline test (#162) and this one of backend request counts by response duration and request type, represented in percentages.  In addition to average VU flow response times and error rates, this may serve as an important means to assess the performance impact of this change.

Only successful requests are represented.  Compared to the previous test, there were 8% fewer backend requests.  Given the test also ran for 3.7% shorter, I wouldn't think the fewer backend requests represent a material difference in system demand.

The larger the percent in the first three to four (overlapping) timespans, the better.  The larger the percent in the last two timespans, the worse.  I haven't looked too closely yet but haven't yet seen anything alarming --in fact, some of the results seem counterintuitive.

(Apologies for the formatting.  Markdown does not appear to support merged cells, at least how I'm creating this from Excel.)

| Endpoint          | < 10 millis |           | < 100 millis |           | < 1 second |           | < 3 seconds |           | 3-10 seconds |           | > 10 seconds |           |
|-------------------|-------------|-----------|--------------|-----------|------------|-----------|-------------|-----------|--------------|-----------|--------------|-----------|
|                   | 07 Jun 24   | 18 Jun 24 | 07 Jun 24    | 18 Jun 24 | 07 Jun 24  | 18 Jun 24 | 07 Jun 24   | 18 Jun 24 | 07 Jun 24    | 18 Jun 24 | 07 Jun 24    | 18 Jun 24 |
| Search            | 2.25%       | 2.78%     | 32.81%       | 30.79%    | 80.93%     | 78.97%    | 100.00%     | 99.96%    | 0.00%        | 0.04%     | 0.00%        | 0.00%     |
| Related Lists     | 0.00%       | 0.00%     | 0.00%        | 0.00%     | 47.31%     | 39.98%    | 92.65%      | 87.68%    | 5.49%        | 10.02%    | 1.87%        | 2.29%     |
| Facets            | 5.56%       | 4.55%     | 26.83%       | 25.61%    | 88.57%     | 86.65%    | 95.54%      | 94.54%    | 2.79%        | 3.18%     | 1.66%        | 2.28%     |
| Search Will Match | 0.71%       | 0.64%     | 15.25%       | 15.79%    | 60.79%     | 60.89%    | 82.57%      | 86.66%    | 2.18%        | 1.89%     | 15.25%       | 11.46%    |
| Search Estimate   | 5.30%       | 4.85%     | 35.37%       | 31.98%    | 98.84%     | 98.62%    | 100.00%     | 100.00%   | 0.00%        | 0.00%     | 0.00%        | 0.00%     |
| Document          | 97.89%      | 97.67%    | 99.98%       | 99.97%    | 100.00%    | 100.00%   | 100.00%     | 100.00%   | 0.00%        | 0.00%     | 0.00%        | 0.00%     |

**Comment by brent-hartwig** [comment]
Even distribution among the three ML nodes:

| Node  | Log     | Count     | %      |
|-------|---------|-----------|--------|
| 217   | request |  94,562   | 33.33% |
| 111   | request |  94,950   | 33.47% |
| 22    | request |  94,210   | 33.21% |
| **Total** |         |  **283,722**  | **100.00%**       |
|       |         |           |        |
| 217   | access  |  92,726   | 33.33% |
| 111   | access  |  93,077   | 33.45% |
| 22    | access  |  92,416   | 33.22% |
| **Total** |         |  **278,219**  | **100.00%** |

Not yet clear why the request logs report higher counts than the access logs for the same time period.  True during the previous test too.

**Comment by brent-hartwig** [comment]
- [ ] Resolved / Understood / Issue Submitted

We may be able to optimize `searchWillMatch` via changes to `relatedListsLib.mjs`'s `PRIORITY_BY_RELATION_KEY`.  That variable may be used to influence the order a related list's triple searches are executed in when only needing to know if a related list has at least one item.  This capability is utilized in the frontend entity page context to determine whether to display a UI widget.  Below is a formatted version of this test's `atLeastOneRelatedListItem.txt` (log mining output).  Related lists without items are filtered out.  Remaining rows are sorted by duration.  While duration for the same request can vary based on concurrent demand, note the number of relations checked, in column B.  The fewer the better in this context.

**Ultimately, this is about how fast an agent, concept, or place entity page begins to render for a user.**  Each associated `searchWillMatch` request includes criteria for four related lists, asking whether they have at least one item. 

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/642f73fa-efeb-43af-88eb-8cb80abf652e)

**Comment by brent-hartwig** [comment]
Backend log findings, and related / follow-up tickets:

1. The only entries above info-level in the main error logs contain "Slow send" and "Clearing expired".  No concerns.
2. Unlike the previous perf test which has [two `XDMP-XDQPINVREQ` instances](https://github.com/project-lux/lux-marklogic/issues/162#issuecomment-2159060714) and **counterintuitive for this test**, no request attempted to transfer too much data between nodes.  Related: monitoring test https://git.yale.edu/lux-its/ml-cluster-formation/issues/25.
3. There were no failed facet requests.  Related: monitoring test https://git.yale.edu/lux-its/ml-cluster-formation/issues/21.
4. No facet requests exceeded the product threshold.  Related: #179 and monitoring test https://git.yale.edu/lux-its/ml-cluster-formation/issues/20.
5. There were no failed related list requests.
6. There were no failed search requests.
7. The related list relations threshold was hit multiple times, as it would have been during previous tests as well.  Related: #30 and monitoring test https://git.yale.edu/lux-its/ml-cluster-formation/issues/23.
8. There were 1,133 `searchEstimate`-related `XDMP-JSONDOC` errors.  Related #183 and monitoring test https://git.yale.edu/lux-its/ml-cluster-formation/issues/24.
9. There were four instances of `Error running JavaScript request: null`.  Unlike [#162's instances](https://github.com/project-lux/lux-marklogic/issues/162#issuecomment-2159189518), these were all associated to `searchWillMatch`, which #177 is to help with in the future.
10. There were six instances of `JS-FATAL` / `JS-BAD` pair errors.  Same as [#162's instances](), these were all associated to `searchWillMatch`.  Hereto, #177 is to help understand more about these, with in the future.
11. There were no other noteworthy findings in the application logs.

**Comment by brent-hartwig** [comment]
Mined output from backend logs:

[2024-06-18-perf-test-request-metrics.xlsx](https://github.com/user-attachments/files/15916939/2024-06-18-perf-test-request-metrics.xlsx)
[2024-06-18-perf-test-all-requests-with-durations.xlsx](https://github.com/user-attachments/files/15916937/2024-06-18-perf-test-all-requests-with-durations.xlsx)
[2024-06-18-perf-test-at-least-one-related-list-item.xlsx](https://github.com/user-attachments/files/15916938/2024-06-18-perf-test-at-least-one-related-list-item.xlsx)
[2024-06-18-perf-test-search-params-and-durations.xlsx](https://github.com/user-attachments/files/15916925/2024-06-18-perf-test-search-params-and-durations.xlsx)
[allFacetRequests.txt](https://github.com/user-attachments/files/15916926/allFacetRequests.txt)
[allFailedFacetRequests.txt](https://github.com/user-attachments/files/15916927/allFailedFacetRequests.txt)
[errorLogEntriesAboveInfo.txt](https://github.com/user-attachments/files/15916928/errorLogEntriesAboveInfo.txt)
[exceededFacetProductThreshold.txt](https://github.com/user-attachments/files/15916929/exceededFacetProductThreshold.txt)
[failedRelatedListRequests.txt](https://github.com/user-attachments/files/15916930/failedRelatedListRequests.txt)
[failedSearchOnlyRequests.txt](https://github.com/user-attachments/files/15916931/failedSearchOnlyRequests.txt)
[hitMaxNumberOfRelations.txt](https://github.com/user-attachments/files/15916932/hitMaxNumberOfRelations.txt)
[oddRelatedListErrors.txt](https://github.com/user-attachments/files/15916933/oddRelatedListErrors.txt)
[searchLongRunning.txt](https://github.com/user-attachments/files/15916935/searchLongRunning.txt)
[searchParamsAndDurations.json](https://github.com/user-attachments/files/15916936/searchParamsAndDurations.json)

**Comment by brent-hartwig** [comment]
- [ ] Acknowledged, understood, issue submitted, or resolved

As with #162 ([in this comment](https://github.com/project-lux/lux-marklogic/issues/162#issuecomment-2155529318)), AWS reported the ML LB returned 1,000s of 504s per minute for the duration of the test while the webcache LB peaked at 265 per minute, excluding a peaks associated with an unexplained dropped in CPU utilization within the ML cluster.

Also same as #162, 8003's request queue was full for most of the test.

Ideas we're tracking to counter this:

* https://github.com/project-lux/lux-middletier/issues/67
* https://github.com/project-lux/lux-marklogic/issues/180
* Increase the ML LB timeout.

**Comment by brent-hartwig** [comment]
- [ ] Acknowledged, understood, issue submitted, or resolved

Since #162, additional logging was enabled in an attempt to better understand the fewer than expected backend requests.  The additional logging gives us response counts by status code throughout the stack.  Below is a to-be-validated table of this information, along with some questions.

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/07e7c0a4-e2dd-4af0-86ad-6e5f0fabf5b7)

#162 comments on the matter: [first](https://github.com/project-lux/lux-marklogic/issues/162#issuecomment-2155520602) and [second](https://github.com/project-lux/lux-marklogic/issues/162#issuecomment-2165908864)

Seong's take on [status code 0](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html) and [status code 460](https://stackoverflow.com/questions/41986890/status-code-460-on-application-load-balancer#answers-header), which I agree with: "It seems, status 0 from CloudFront and 460 from web cache and middle tier, they mean the same thing: client closed connection before server could respond. They are not standard HTTP status codes  -- they cannot be returned to the client after all."

**Comment by brent-hartwig** [comment]
- [ ] Acknowledged, understood, issue submitted, or resolved

### CPU Utilization Node Variance

CPU utilization was above 90% 27 of 399 data points.  While that averages to 9 of 133 data points per node, it turns out:

* Node 22: Never exceeded 89.16%.  22 data points between 85% and 90%.
* Node 111: Exceeded 90% three times with a max of 91.41%.  30 data points between 85% and 90%, or 33 of 133 data points at 85% or more.
* Node 217: Exceeded 90% **24 times** with a max of 94.47%.  61 data points between 85% and 90%, or **85 of 133 data points at 85% or more**.

As detailed in [this comment](https://github.com/project-lux/lux-marklogic/issues/181#issuecomment-2180497376), node 217 processed 33.33% of the requests.

**Takeaway:** node 217 is taxed more than the other two nodes --possibly enough to investigate and/or monitor.

**Comment by brent-hartwig** [comment]
- [ ] Acknowledged, understood, issue submitted, or resolved

After adding data from QA's report, we were able to complete this test's column in the key metrics spreadsheet.

Here is a comparison of this test to its baseline:

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/7dce824e-76c0-40b8-b8df-2d115edae7e2)

Highlights of the comparison:

1. Both tests had an overall error rate of 4.41% --a positive indicator.
1. The eight VU flows (a.k.a., transactions) with individual error rates of 10% or greater were the same in both tests.
    * Four had greater error rates in the latest test, ranging from 0.59% to 9.47%.  The flow with the largest increase in was "Lux_Events_tab".
    * The other four had smaller error rates in the latest test, ranging from 1.73% to 17.87%.  The flow with the largest decrease was "Lux_Objects_Faucets".
    * Unknown to what degree that these flow-level error rate changes are due to the change being tested.
1. In three of the four individual VU flows we track, this test was faster with three of them, including simple search --opposite of what one may have expected.
1. This test had a faster average, unweighted VU response time --another surprise.
1. This test took CPU utilization from 90.32% to 94.47%.  Note that one node was taxed more than the other two, which is detailed in [the CPU Utilization Node Variance comment](https://github.com/project-lux/lux-marklogic/issues/181#issuecomment-2183093421).
1. The backend request count was inline with the baseline test.  Separately, we are still looking into the lower than expected backend request counts; see the [stack response count analysis comment](https://github.com/project-lux/lux-marklogic/issues/181#issuecomment-2182764059) for an analysis of the load balancers.
1. In both tests, 8003's request queue reported full for most of the test.  Here too, we continue to look into it; for more, see the [504s comment](https://github.com/project-lux/lux-marklogic/issues/181#issuecomment-2182636931).

**Comment by brent-hartwig** [comment]
Closing this ticket as all findings have been "acknowledged, understood, issue submitted, or resolved".  cc: @jffcamp
