### ISSUE TITLE
Performance Test - scheduled for 2024-07-17

### ISSUE THREAD

**Issue by jffcamp** [project-lux/lux-marklogic#226]
_This was the first performance test executed by NeoLoad._

## Primary Objective
We will be following scenario AM, which is similar to scenario J but with Advanced Search Configuration and Data Contants being moved from Group-1 to Group-2. This was done to minimize errors during the performance test.
[Scenario AM](https://docs.google.com/spreadsheets/d/1uu6aL7yn047yyiZ4auujpTXnlwm01sgWZQ50ht-X4M4/edit#gid=593469390) and state the primary objective.

The purpose of this test is to validate that ML 11.3 performs sufficiently to be moved to production with the 7/29 Blue/Green switch.

## Changes Being Tested

We are primarily testing an upgrade to ML 11.3.0 GA, with the 2024-05-29 dataset.

* [#162's performance test](https://github.com/project-lux/lux-marklogic/issues/162) was in Green with 11.0.3 GA with remnants of a 11.2 nightly build, also with the 2024-05-29 dataset.
* [#181's performance test](https://github.com/project-lux/lux-marklogic/issues/181) was in DEV with 11.2.0 GA, with the 2024-05-14 dataset (questionable).

Other changes compared to both previous perform tests:

* https://github.com/project-lux/lux-middletier/issues/77: performance improvement on the search results page
* https://github.com/project-lux/lux-middletier/issues/78: from request-group-1 to request-group-2
* First full performance test using NeoLoad.

### Environment and Versions

- Environment: TST which is configured to the **BLUE** backend.
- MarkLogic **11.3.0 GA.**  As part of the upgrade from ML 11.0.3 GA, the /var/opt/MarkLogic data directory was deleted to ensure there were no remaining remnants of a ML 11.2.0 nightly build.
- Backend **v1.21.0 WIP.**  At the time, the only runtime change since v1.20.0 was the split of an error check within `_getSearchTermConfig`.
- Middle Tier **77-78-test-2**
- Frontend **v1.30.0**
- Dataset produced on **5/29/24**

### Backend Application Server Configuration

- lux-request-group-1 on port 8003: The middle tier is expected to send all requests here document, facets, searchEstimate, searchInfo, searchWillMatch, stats, translate, autoComplate
Maximum of 6 concurrent requests.
- lux-request-group-2 on port 8004: The middle tier is expected to send relatedList, search, advancedSearchConfig, dataConstants requests here.  Maximum of 12 concurrent requests.
- Maximum of 18 concurrent requests per node.

## Tasks

For more information please see the documentation: [LUX Performance Testing Procedure](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md)

### Prep, Start, and Preliminary Checks

- [x] Confirm the most recent blue-green switch is 100% complete (i.e., no part of TST is using PROD).
- [x] Deploy code and/or configuration changes that are being tested.
- [x] Disable middle-tier caching in TST ([instructions](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md#disable-middle-tier-caching)).
- [x] Verify LUX trace events are enabled plus `v8 delay timeout`.
- [x] Smoke test the front end.
- [x] Start collecting OS-level metrics ([instructions](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md#start-collecting-os-level-metrics)).
- [x] Start collecting middle tier metrics ([script](https://git.yale.edu/lux-its/marklogic/blob/main/scripts/getMiddleTierStats.sh))
- [x] QA: Verify/set ramp-up schedule to 2 simple search VUs, 1 filtered VU, and 1 entity page VU every three minutes until there are 148 users then hold for 15 minutes **<-- initially true but changed after at least one failed test.  See [this comment](https://github.com/project-lux/lux-marklogic/issues/226#issuecomment-2239091670) for the final ramp-up schedule.**
- [x] QA: Verify test is configured with three second wait times.
- [x] QA: Verify scripts point to TST, https://lux-front-tst.collections.yale.edu/
- [x] Team: Sign off on the above before proceeding.
- [x] QA: Start performance test. ~ 12:45
- [x] Team: begin monitoring for v8 engine crashes.
- [x] Team: check total request count at 10 minutes.
- [x] Team: check total request count at 15 minutes.
- [x] Team: check total request count at 20 minutes.
- [x] QA: Finish performance test.

### Collect data

- [x] Stop collecting OS-level metrics and attach to the ticket.
- [ ] Stop collecting middle-tier metrics and attach to the ticket.
- [ ] Collect data from AWS and attach to ticket.
- [x] Collect ML monitoring history ([instructions](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md#backend-monitoring-history)).
- [x] Collect ([script](https://github.com/project-lux/lux-marklogic/blob/main/scripts/logAnalysis/collectBackendLogs.sh)), trim ([script](https://github.com/project-lux/lux-marklogic/blob/main/scripts/logAnalysis/trimBackendLogs.sh)), and attach backend logs to the ticket.
- [x] Pull app server queue metrics ([script](https://github.com/project-lux/lux-marklogic/blob/main/scripts/extractAppServerQueueMetrics.js)), attach to the ticket, and record in [Perf: Key Metrics](https://docs.google.com/spreadsheets/d/1uu6aL7yn047yyiZ4auujpTXnlwm01sgWZQ50ht-X4M4/edit#gid=774672157).  *Starting in ML 11.2.0, this information may be included in the ML monitoring history screenshots and exports.*
- [x] Update online spreadsheet tabs with what is known at this point.

### Restore and Verify Environment

- [ ] Revert this test's code and configuration changes
- [ ] Enable middle-tier caching ([instructions](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-performance-testing.md#enable-middle-tier-caching)).
- [ ] Smoke test the front end.

### Analyze

- [x] Upon receipt, review report from QA and update related portions of the online spreadsheet tabs.
- [x] Mine the backend logs.
- [x] Determine if the test is valid: Considered valid despite the NeoLoad implementation of the test being in flux and not directly comparable to the previous tests.
- [x] Determine if the performance is acceptable.  Team agrees we can go forward with ML 11.3.0 GA.

**Comment by brent-hartwig** [comment]
## ML Monitoring History

Time period: 19:50 - 20:20 UTC (last test of the day with aggressive ramp up; 8 - 12 minutes at 145 users)

CPU:

![01-cpu](https://github.com/user-attachments/assets/2aa15edc-d7d1-4343-ad76-3adc473ea631)

File IO Detail:

![02-io](https://github.com/user-attachments/assets/d60b571a-5ecd-4396-a907-6793f1ff4b86)

Memory:

![03-memory](https://github.com/user-attachments/assets/ce5edd3a-1350-4eab-8c47-0973dda708e5)

Intra-cluster activity, 1 of 2:

![intra-1-of-2](https://github.com/user-attachments/assets/01ac3754-a61a-47f9-9885-6b7d3856885f)

Intra-cluster activity, 2 of 2:

![intra-2-of-2](https://github.com/user-attachments/assets/3a7b23f5-b821-4963-829a-ce52c29813ba)

Data node characteristics for the `lux-content` database alone:

![07-database](https://github.com/user-attachments/assets/e48af15a-e568-4e0c-b485-2244b9e0a162)

Exports:

[memory-detail-20240718-175928.xls](https://github.com/user-attachments/files/16287282/memory-detail-20240718-175928.xls)
[network-detail-20240718-180345.xls](https://github.com/user-attachments/files/16287283/network-detail-20240718-180345.xls)
[servers-detail-20240718-180623.xls](https://github.com/user-attachments/files/16287284/servers-detail-20240718-180623.xls)
[xdqp-server requests detail-20240718-180259.xls](https://github.com/user-attachments/files/16287286/xdqp-server.requests.detail-20240718-180259.xls)
[cpu-detail-20240718-175455.xls](https://github.com/user-attachments/files/16287287/cpu-detail-20240718-175455.xls)
[databases-detail-20240718-180643.xls](https://github.com/user-attachments/files/16287288/databases-detail-20240718-180643.xls)
[file-i_o detail-20240718-175825.xls](https://github.com/user-attachments/files/16287289/file-i_o.detail-20240718-175825.xls)

**Comment by xinjianguo** [comment]
Status code counts
2024-07-17 19:50:00 - 20:20:00 UTC or 15:50:00 - 16:20:00 EDT

CloudFront (non-frontend routes):
```
select sc_status,count(*) as count
from lux_cloudfront_tst 
where date=date('2024-07-17') and time between '19:50:00' and '20:20:00' 
group by sc_status 
order by sc_status;
```
<img width="362" alt="Screen Shot 2024-07-18 at 4 12 40 PM" src="https://github.com/user-attachments/assets/8662a6b2-f53a-4a58-94d9-a1211e5bef24">

WebCache ALB:
```
select elb_status_code,target_status_code,count(*) as count
from lux_alb_webcache_blue 
where time between '2024-07-17T19:50:00.000000Z' and '2024-07-17T20:20:00.000000Z' 
group by elb_status_code,target_status_code 
order by elb_status_code,target_status_code;
```
<img width="468" alt="Screen Shot 2024-07-18 at 4 01 56 PM" src="https://github.com/user-attachments/assets/4cc75d21-5029-41cd-82b2-f59613a2b064">

Middle tier ALB:
```
select elb_status_code,target_status_code,count(*) as count
from lux_alb_middle_blue 
where time between '2024-07-17T19:50:00.000000Z' and '2024-07-17T20:20:00.000000Z' 
group by elb_status_code,target_status_code 
order by elb_status_code,target_status_code;
```
<img width="472" alt="Screen Shot 2024-07-18 at 3 59 03 PM" src="https://github.com/user-attachments/assets/3595db00-4805-4a02-bba0-a022bdac2c03">

MarkLogic ALB:
```
select elb_status_code,target_status_code,count(*) as count
from lux_alb_marklogic_blue 
where time between '2024-07-17T19:50:00.000000Z' and '2024-07-17T20:20:00.000000Z' 
group by elb_status_code,target_status_code 
order by elb_status_code,target_status_code;
```
<img width="471" alt="Screen Shot 2024-07-18 at 4 19 09 PM" src="https://github.com/user-attachments/assets/473b5b20-8589-4df4-9e53-c041dd336d07">

**Comment by brent-hartwig** [comment]
Thanks for the request counts and queries, @xinjianguo!

**Comment by brent-hartwig** [comment]
Based on the following chart from QA's report, the ramp up schedule was five VUs every minute for 24 minutes until reaching a peak of 120 for just over a minute before a steep drop off (presumed NeoLoad crash).

![image](https://github.com/user-attachments/assets/030b0c80-f9ea-4ffe-b515-b4e65a3a888a)

**Comment by brent-hartwig** [comment]
Trimmed backend logs: [20240717-blue-as-test-backend-logs-trimmed.zip](https://github.com/user-attachments/files/16312800/20240717-blue-as-test-backend-logs-trimmed.zip)

**Comment by brent-hartwig** [comment]
Backend log mining output: [20240717-1950-2020-mined-log-output.zip](https://github.com/user-attachments/files/16313407/20240717-1950-2020-mined-log-output.zip)

**Comment by brent-hartwig** [comment]
During #181's performance test, node 217 had a higher CPU utilization than the other two nodes ([#181's CPU utilization comment](https://github.com/project-lux/lux-marklogic/issues/181#issuecomment-2183093421)).  This time, that was the case for node 22: node 22 had 17 of the 18 data points when utilization was over 95%.  As part of the upgrade, all of Blue's nodes received new ec2 instances.

![image](https://github.com/user-attachments/assets/b4ba7b33-37f5-48f9-8745-63f487672993)

**Comment by brent-hartwig** [comment]
The ratio of requests by type appears to have changed between LoadRunner and NeoLoad.  The team concluded the NeoLoad version is still in flux and thus any comparisons could be questionable.  Nonetheless, capturing here as the work was done.

![image](https://github.com/user-attachments/assets/fb2fdd97-bd85-4bfe-be30-053d6d2e8e42)

Tables supporting the above table:

![image](https://github.com/user-attachments/assets/81c28446-d034-4559-ab1e-4f47ccc99c29)

![image](https://github.com/user-attachments/assets/b32f7b5f-f76c-47e1-8997-5045711d6c8a)

![image](https://github.com/user-attachments/assets/a1d96b41-8d9b-4031-8190-cd280a9e420f)

**Comment by brent-hartwig** [comment]
Caveated, we experienced a decrease in 504s received by the MarkLogic load balancer.

During 18 Jun's performance test, there were 3x as many 504s at the ML load balancer than ML processed.  During this test, it was only 0.22x.  This reduced pressure on the data service retry mechanism.  Rerouting advancedSearchConfig and dataConstants requests may have helped somewhat; however, due to differences between the LoadRunner and NeoLoad implementations of the test, the ratio of requests by type was significantly different including thousands fewer advancedSearchConfig and dataConstants requests than anticipated.  For more on the request type composite change, see [this comment](https://github.com/project-lux/lux-marklogic/issues/226#issuecomment-2239459804).

![image](https://github.com/user-attachments/assets/b8b1d82f-635e-4c0b-b2f9-a736c3ebeffb)

**Comment by brent-hartwig** [comment]
Other observations copied from Teams...

Per CPU utilization, we know the NeoLoad test pushed MarkLogic hard and that neither the v8 engine crashed nor MarkLogic process restarted --all good.

But I otherwise find it hard to compare yesterday's test to the previous tests.

A metric I like checking is the number of facet requests per search request.  During the 18 Jun test, there were 11.86 facet requests per search request.  During yesterday's test, there were only 6.10 facet requests per search request.  That's someone concerning given all/most search results tabs have more than six facets.

I find it odd that there were over 18K fewer than expected advanced search configuration and data constant requests (combined) but doubt that had a material effect given they are the equivalent of document requests, as they are all very lightweight requests.

I am surprised that there were _any_ failed advanced search configuration or data constants requests given the successful requests were served up by the second app server and that app server never registered any queued requests.

**Comment by brent-hartwig** [comment]
## Executive Summary

* MarkLogic 11.3.0 is approved for production.
* We are to rethink our approach to performance testing.  We need to avoid making accommodations for the performance test and should have the web cache enabled, as it always is in production.
* We are to update the performance test to align with present-day production usage.
* No need to spend additional cycles trying to reconcile differences between LoadRunner and NeoLoad.
