### ISSUE TITLE
Search timed out due to omitted Hop Inverse search criteria

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#260]
**Problem Description:**
Rob reported the following search timed out.  The timeout is due to every word in "Without from within" being a stop word and that the phrase was not quoted.  The search was allowed to proceed because there was other search criteria.  Yet, we should question this as when a Hop Inverse search term's criteria is omitted, all triples for the specified predicate are included in the search, leading to the timeout.

Search criteria:

```json
{
  "_scope":"agent",
  "AND":[
    {
      "name":"Djanogly Art Gallery"
    },
    {
      "created":{
        "name":"Without from within"
      }
    }
  ]
}
```

Generated query from Backend v1.21 for the above criteria: [stop-word-timeout.js.txt](https://github.com/user-attachments/files/16431111/stop-word-timeout.js.txt)

**Expected Behavior/Solution:**
Consider possible responses, including:

1. User training: quote phrases
2. Frontend to enable user to add `_complete: true` to search terms.
3. Automatically quote, potentially limited to a subset of search terms.  If the user wanted to AND the individual words, they would need to enter them separately.
4. Reject the request when all of a Hop Inverse term's criteria is omitted.
5. Implement the optimization first discussed in #113 whereby you move criteria into the call to `cts.triples` without changing the meaning of the query.  In this case, using [stop-word-optimized.js.txt](https://github.com/user-attachments/files/16431115/stop-word-optimized.js.txt), zero results were returned in 127 ms.
10. Introduce a new data cap.  Results for this query using [stop-word-data-cap.js.txt](https://github.com/user-attachments/files/16431124/stop-word-data-cap.js.txt):
    * Cap of 100K returned zero results in 2,200 ms.
    * Cap of 250K returned one result in 5,300 ms.
    * Cap of 400K returned two results in 8,500 ms.
    * Cap of 500K, returned two results in 10,500 ms.
    * ^-- results are likely false positives as stop words were omitted.

**Requirements:**
**TODO:** List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~- [ ] Wireframe/Mockup - Mike~
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
**TODO:** Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**
This issue neither blocks nor is blocked by another.

**Related Github Issues:**

* #113 originally identified a related optimization
* Potentially the same issue that #33 wants to address.
* If left unresolved, #273 has the potential to interfere with the user training suggestion of quoting the phrase.  #273 is only a problem when the same advanced search field contains a phrase and at least one other phrase or word.

**Related links:**
None

**Wireframe/Mockup:**
N/A

**Comment by brent-hartwig** [comment]
@clarkepeterf, do you mind filling the rest of this out so it can be prioritized?

**Comment by clarkepeterf** [comment]
Adding to to-do for tomorrow

**Comment by clarkepeterf** [comment]
Propose close - #33 is a fix for this issue

**Comment by roamye** [comment]
Approved by UAT 9/12 to close.
