### ISSUE TITLE
META: Add Facets For Other Scope's Data Types (from 1098)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#42]
### Problem Description
Currently there exists the facet People or Groups to filter "People & Groups:" (agents) by their data type. This does not exist for any other scopes

Extension: these options will also need to be added to Advanced Search

### Questions:
- [x] - What are the options/opportunities for Objects and Works?
- [x] - Is there anything else to consider for Events, Concepts, Places?

### Expected Outcome:
Create facets for other scopes
- [ ] Events - faceting by class of event instance
  - facet name: Event Class
  -- value: Period
  -- value: Activity
- [ ] Concepts - faceting by class of concept instance
  - facet name: Concept Class
  -- value: Measurement Unit  - 'MeasurementUnit' (units such as cm, inches, etc..)
  -- value: Language - 'Language'
  -- value: Material - 'Material' 
  -- value: Currency - Currency
- [ ] Works
  -  facet name: Work Class
  -- value: Visual Work - 'VisualItem'
  -- value: Textual Work - 'LinguisticObject'
- [ ] Objects
  - facet name: Object Class
  -- value: Physical Object - 'HumanMadeObject',
  -- value: Digital Object - 'DigitalObject'
- [x] ~People and Groups~ (DONE)
  -- ~facet name: Person or Group~
- [x] Places
  - Not needed because there is only one 'Place' type. 
 
### Needed

- [X] Front end ticket with wireframe 
- [x] Is Middle Tier ticket needed? No
- [x] Determine which scopes need this facet (all except Places?)
- [x] Determine names for each facet
- [x] Determine display names for Types. (e.g. LinguisticObject would display as Textual)

**Blocked/Dependencies:** 
Blocking: 
- [ ] Event FE: https://github.com/project-lux/lux-frontend/issues/175
- [ ] Concept FE: https://github.com/project-lux/lux-frontend/issues/176
- [ ] Work FE: https://github.com/project-lux/lux-frontend/issues/177
- [ ] Object FE: https://github.com/project-lux/lux-frontend/issues/178

### Links
- Related, but not directly connected front-end ticket: https://github.com/project-lux/lux-frontend/issues/68
- https://www.bugherd.com/projects/284041/tasks/1784
- Old ticket: https://git.yale.edu/lux-its/marklogic/issues/1098

**Comment by ar2674** [comment]
@miketullo95 should this be assigned to you instead?

**Comment by miketullo95** [comment]
@ar2674 yep! thanks

**Comment by roamye** [comment]
conversation from old ticket: 
---------------
@prowns I'd like to mark this issue for forming.

Created with @kd736 based on a bugherd. I'm not sure who should decide on what to call the facets.

_Originally posted by @pc754 in https://git.yale.edu/lux-its/marklogic/issues/1098#issuecomment-24145_
------------
 I think the review process would be that @hw396 preps a wireframe with proposed facet labels to bring to Interactions for naming.

_Originally posted by @prowns in https://git.yale.edu/lux-its/marklogic/issues/1098#issuecomment-24147_            
----------------
 I'm going to assign @hw396 so that she can work the wireframe + labels

_Originally posted by @pc754 in https://git.yale.edu/lux-its/marklogic/issues/1098#issuecomment-24168_

**Comment by roamye** [comment]
@miketullo95 will prioritize meta tix to create mockups for facets + advanced search. thank u

**Comment by roamye** [comment]
mockups for all child tickets should be updated to reflect those in this comment: https://github.com/project-lux/lux-frontend/issues/176#issuecomment-2059560556

**Comment by roamye** [comment]
Other tickets have been updated to reflect the discussion in BA/UX meeting. However, per the meeting we need clarification on where the data for the sub-tickets are coming from. Is the data already existing? 

For example, Work Class will have the option for Visual Work. However, we can filter by Visual Work through Work Type facet. 
Does adding Work Class cause a redundancy?

Will be brought to Team Meeting to clarify. Afterward @miketullo95 will work on updating the AS mockups for the child tickets. 

cc: @prowns

**Comment by roamye** [comment]
From teams meeting last week 4/18 - the data comes from the same model as people or groups. So it is different data than we had thought from the comment above. Mike to work on updating the AS mockups for the child tickets. @miketullo95

**Comment by prowns** [comment]
Ok to close from UAT, as the issues all have their own tickets now.
